POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "Suu Nguyen",
    "username": "itdev126",
    "password": "123456",
    "email": "itdev.126@gmail.com",
    "role": 1
}
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "itdev126",
    "password": "123456"
}

###
PUT http://localhost:8080/api/auth/edit-user-info/1
Content-Type: application/json

{
    "name" : "SN",
    "email": "itdev.126@gmail.com",
    "address": "Vietnam",
    "about" : "I'm a software engineer",
    "cookpadId": "itdev126_"
}
